### ISSUE TITLE
`brew install sqld-beta` fails on wsl windows

### ISSUE THREAD

**Issue by nkilm** [libsql/homebrew-sqld#4]
## Description
I am following the instructions on this link https://github.com/libsql/sqld/blob/main/docs/BUILD-RUN.md#build-and-install-with-homebrew.

Screenshot of the error attached for reference.

> ![image](https://github.com/libsql/homebrew-sqld/assets/79012023/afb3d4a4-21d7-45e3-a5da-669725fd0342)

Prior to this, the command had failed because I didn't have `gcc` installed in my wsl environment. 

### Information about my current environment

I am trying to setup [this](https://github.com/openstatusHQ/openstatus) project locally and it requires [this](https://github.com/openstatusHQ/openstatus/blob/main/packages/db/README.md) to be installed locally on the machine. 

Host OS - **Win 10 Home 64bit**
WSL - **Ubuntu 20.04.6 LTS**

**Comment by AkshayBhimani** [comment]
Same error. I got this error while executing `brew install sqld-beta`. 
Can help here?

**Comment by AkshayBhimani** [comment]
[https://stackoverflow.com/questions/64880598/no-function-or-associated-item-named-new-v3-found-for-struct-uuiduuid-in-the-c](stackoverflow-url) might help to solve this issue.

**Comment by nkilm** [comment]
Yes I did check this 

> [https://stackoverflow.com/questions/64880598/no-function-or-associated-item-named-new-v3-found-for-struct-uuiduuid-in-the-c](stackoverflow-url) might help to solve this issue.

Yes I did check this solution before I opened an issue here. But it seems to be the problem in the source code not with my|yours system.

**Comment by CodingDoug** [comment]
This should be fixed now with 0.17.2.  `brew install sqld-beta` works for me on macos and wsl.

See: https://github.com/libsql/sqld/pull/566

**Comment by nkilm** [comment]
@CodingDoug Thanks it's working now!

**Comment by hrutik7** [comment]
not working !
